<?xml version="1.0" encoding="utf-8"?>

<Project Sdk="Microsoft.NET.Sdk.Razor">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <StaticWebAssetBasePath>App_Plugins/$(AssemblyName)</StaticWebAssetBasePath>
  </PropertyGroup>

  <PropertyGroup>
    <VersionPrefix>13.0.0</VersionPrefix>
    <VersionSuffix Condition="'$(Configuration)'=='Debug'">build$([System.DateTime]::UtcNow.ToString(`yyyyMMddHHmm`))</VersionSuffix>
    <Company>Limbo</Company>
    <Product>Limbo Multinode Treepicker</Product>
    <Authors>Anders Bjerner</Authors>
    <Copyright>Copyright © $([System.DateTime]::UtcNow.ToString(`yyyy`))</Copyright>
    <Title>Limbo Multinode Treepicker</Title>
    <AssemblyTitle>Limbo Multinode Treepicker</AssemblyTitle>
    <Description>Extended multi node tree picker for Umbraco.</Description>
  </PropertyGroup>

  <!-- Include additional metadata in the assembly -->
  <ItemGroup>
    <AssemblyMetadata Include="PackageProjectUrl" Value="https://packages.limbo.works/limbo.umbraco.multinodetreepicker/" />
    <AssemblyMetadata Include="DocumentationUrl" Value="https://packages.limbo.works/limbo.umbraco.multinodetreepicker/docs/v13/" />
    <AssemblyMetadata Include="NuGetUrl" Value="https://www.nuget.org/packages/Limbo.Umbraco.MultiNodeTreePicker" />
    <AssemblyMetadata Include="UmbracoMarketplaceUrl" Value="https://marketplace.umbraco.com/package/limbo.umbraco.multinodetreepicker" />
  </ItemGroup>

  <!-- Information for the NuGet package -->
  <PropertyGroup>
    <PackageId>Limbo.Umbraco.MultiNodeTreePicker</PackageId>
    <PackageTags>Limbo, Skybrud, Umbraco, MNTP, MultiNodeTreePicker, Umbraco-Marketplace</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://packages.limbo.works/limbo.umbraco.multinodetreepicker/</PackageProjectUrl>
    <PackageIcon>Limbo.png</PackageIcon>
    <PackageReadmeFile>NUGET.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/abjerner/Limbo.Umbraco.MultiNodeTreePicker</RepositoryUrl>
  </PropertyGroup>

  <!-- Include NuGet dependencies -->
  <ItemGroup>
    <PackageReference Include="Skybrud.Essentials" Version="1.1.57" />
    <PackageReference Include="Umbraco.Cms.Core" Version="[13.0.0,13.999)" />
    <PackageReference Include="Umbraco.Cms.Web.Website" Version="[13.0.0,13.999)" />
    <PackageReference Include="Umbraco.Cms.Web.BackOffice" Version="[13.0.0,13.999)" />
  </ItemGroup>

  <!-- Include package icon and readme file for the NuGet package -->
  <ItemGroup>
    <Content Include="../build/Limbo.png" Pack="true" PackagePath="\" />
    <None Include="..\..\NUGET.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <!-- Exclude files from the NuGet package -->
  <ItemGroup>
    <Content Remove="compilerconfig.json" />
    <Content Include="compilerconfig.json" Pack="false" />
  </ItemGroup>

  <!-- Generate XML documentation -->
  <PropertyGroup>
    <DocumentationFile>bin\$(Configuration)\$(TargetFramework)\$(AssemblyName).xml</DocumentationFile>
  </PropertyGroup>

</Project>